
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package year;
//Imports
import year.Home;
import year.User;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author abisulco
 */
public class Delete extends javax.swing.JFrame {
public String teacherName;//teachername object to be used in order to find removalable teachers
public User u;//Object to past data from form to form
    /**
     * Creates new form Remove
     */
    public Delete(User r) {
        initComponents();//sets up screen
        teacherName=r.getTeacher();//teacher name is set 
        u=r;//users object is stored in this class
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     //Generated code by netnean gui builder Begining
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Number to delete:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jButton1)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton2)
                        .add(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(64, 64, 64)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(20, 20, 20))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton2)
                        .add(59, 59, 59)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Generated code by netnean gui builder End
    //Back to main form
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);//current form is made invisible
        new Home(u).setVisible(true);//home form is made visible
     
     
    }//GEN-LAST:event_jButton2ActionPerformed
//form is loaded with a list of all occurences of this teachers name in the list
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     ArrayList<String> kol=u.find(teacherName);//find the occurences of the teachername in the bookings array
     DefaultListModel model1 =new DefaultListModel(); //a new model is created in order to display all found occurences
     

     for(int i=0;kol.size()>i;i=i+1){//Goes through the arraylist
            int x=Integer.parseInt(kol.get(i).substring(2));//gets the day from the array lists element
            Calendar caq=Calendar.getInstance();//makes a calendar object with current date
	    caq.set(Calendar.DAY_OF_YEAR, x);//sets a calendar with the day of the year
            String e=(caq.get(Calendar.MONTH)+1)+"/"+caq.get(Calendar.DATE)+"/"+caq.get(Calendar.YEAR);//gets a m d y from the 0-364 day of the year value
           model1.addElement(String.valueOf(i)+u.returnCl(Integer.parseInt(kol.get(i).substring(0,1)))+" Period"+(Integer.parseInt(kol.get(i).substring(1,2))+1)+" Day"+e);//displays cl # date and period of booking
    }
     jList1.setModel(model1);//displays list
     
    }//GEN-LAST:event_formWindowOpened
//Used in order to delete booking
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ArrayList<String> kol=u.find(teacherName);//finds all occurences of teacher name
        if(jTextField1.getText().length()==0){//checks if the number you want to delete is entered
            
        }else{
            int d=0;//sets up the number you want to delete
            try{ 
               d=Integer.parseInt(jTextField1.getText());//checks if the number you want to delete is a number and parses it to a number
               
            } 
            catch (NumberFormatException e){ //if the data entered is not a number then a NAN message is displayed
              JOptionPane.showMessageDialog(null, "ERROR Number was not entered");  
             return;   
             }                  
           if(kol.size()-1<d){//Checks if the number you entered is greater then the number of bookings found
               JOptionPane.showMessageDialog(null, "ERROR Not that many list items");  
           }else{
          
          u.delete(teacherName,d);//deleted the booking found
          
           }
        }
        this.formWindowOpened(null);//refreshes found bookings screen
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
